#define LANG 42
#define MSG_COUNT 43
#define DOWNLOAD_PATH 6
#define DOWNLOAD_PATH_BUTTON 10
#define CLOSE_TO_TRAY 11
#define BALLOON 12
#define UPDATES 44
#define NO_IMAGES 13
#define SMALL_IMAGES 14
#define BIG_IMAGES 15
#define EMOJIS 16
#define SPOILERS 17
#define COLOR_MAIN 45
#define COLOR_CHAT 46
#define COLOR_DLG 47
#define COLOR_TEXT 48
#define COLOR_SELECT 49
#define COLOR_DEFAULT 53
#define CHAT_THEMES 57
#define FONT_CHAT 32
#define FONT_SYSTEM 33
#define FONT_UI 34
#define FONT_SELECT 35
#define FONT_DEFAULT 38
#define SOUND1 7
#define SOUND2 8
#define SOUND3 9
#define SOUND_BUTTON 18
#define SOUND_BUTTON_X 21
#define SAMPLE_RATE 24
#define BITS_PER_SAMPLE 25
#define CHANNELS 26
#define PROXY_IP 27
#define PROXY_PORT 28
#define PROXY_USERNAME 29
#define PROXY_PASSWORD 30
#define PROXY_PASSWORD_HIDE 31